### PR TITLE
Setup prettier, eslint and all that

### PR DESCRIPTION
**Pull request by jfranciscosousa**
Added a bunch of Eslint rules and made prettier work nicely with eslint.

### CODE REVIEW

**Review by SaraVieira — APPROVED** [review]

**Comment by SaraVieira** [comment]
Seems there is a TS error

**Comment by jfranciscosousa** [comment]
@SaraVieira don't merge yet I've found something

**Comment by SaraVieira** [comment]
Mysterious, what did you find???

**Comment by jfranciscosousa** [comment]
New line errors on windows lol. Fixed it. Also removed `async` usages otherwise we were having like 20kb of code from the `asyncRegeneratorRuntime`

**Comment by SaraVieira** [comment]
Shit, I merged the other one first and now there's a lot of conflicts

**Comment by jfranciscosousa** [comment]
@SaraVieira fixed that

**Pull request merged**
